### ISSUE TITLE
知乎也被屏蔽了？

### ISSUE THREAD

**Issue by BorLee** [Feiox/useless-websites#18]
知乎的质量这么低了么？

**Comment by EchoChan314** [comment]
也是醉了，知乎的好多回答质量还是很高的。

**Comment by Feiox** [comment]
@BorLee @czmecho 实在抱歉，不知怎么误加了知乎。我在考虑最近重构该项目。

**Comment by EchoChan314** [comment]
@Feiox 还有中文版的维基百科也在。。。
zh.wikipedia.org

另外，导入到uBlock Origin 怎么用？我导入后搜索结果还是出现那些网站，好像没办法替代Personal Blocklist 的功能。

**Comment by Feiox** [comment]
@czmecho 抱歉，我说怎么最近搜不到维基了。看来我要好好清查一下这个列表了。
uBlock Origin  我没用过。
我一直想重构这个项目，想自己重写一个 Chrome 扩展。Personal Blocklist 很多功能太难用，而且，有时候点错误添的网站很难发现。所以，你在这方面有什么好的建议吗？

**Comment by nopyhe** [comment]
@Feiox 
知乎和中文维基又被加进去了？

**Comment by Feiox** [comment]
已全部更新并重新整理，目前已收录 13400余个。
