### ISSUE TITLE
请添加对垃圾网站的定义

### ISSUE THREAD

**Issue by wchen9** [Feiox/useless-websites#21]
这个项目readme中对垃圾网站的定义：
- 堆砌关键词换取 SEO，本身并无任何价值
- 虚假搜索引擎，例如 问叔叔搜索、森林搜索、谷粉搜搜（假）
- 恶意爬虫内容聚合站，例如 人人 IT
然而，实际上您仓库的列表并不只是这些，还包括 iteye, tieba.baidu.com。请问楼主，这样偏向性明显的列表适合放出来给别人使用吗？这样跟gfw的内容过滤也差不多了吧，只不过是被圈在了这个列表中而已。
这样做也不是不行，至少您得说明一下吧？
今天偶然对某个搜索结果点击了下显示所有结果，然后发现贴吧的一个精品帖子，正好解决的要搜索的问题，感觉非常生气。我想这不是您的本意，现在Google中文搜索结果质量很差，有这样的列表确实能方便很多，我想，这样的列表应该是中立不带立场的，这样更适合一般人使用。
或者，您在readme里面把您倾向性的屏蔽说清楚。不然没有仔细审核过这个列表的人直接用了，恐怕想要的结果不是他们想要的。

**Comment by Feiox** [comment]
抱歉，最近工作有点繁忙而混乱，我并不是有意屏蔽 tieba.baidu.com 。由于缺乏维护，这个项目其实已经暂停了，但我忘记更新 Readme，给您带来麻烦我非常抱歉。
至于混进去  tieba.baidu.com 这类网址，之前也出过混进去 zhihu.com 的疏忽。其原因是，呃，Chrome 的插件有时候会卡顿，一卡就容易误点了两个网址。
但我最近打算重启这个项目，从采集收录，到新版浏览器扩展，以及审核讨论机制。所以，您是否有兴趣一起来维护这个项目呢。
再一次表示歉意。
